units: m
ball_radius: 0.065
line_width: 0.05

mark_width: 0.1

field_length: 9
field_width: 6
goal_depth: 0.6
# Distance between inner edges of goal posts.
goal_width: 1.89
goal_area_length: 0.61
goal_area_width: 3.50
# Height to the bottom of the crossbar.
goal_crossbar_height: 1.20
# The crossbar diameter and the goalpost diameter are (supposed to be) equal.
goalpost_diameter: 0.11
goal_crossbar_diameter: 0.11
goal_net_height: 1.0
# Measured from the goal line.
penalty_mark_distance: 1.80
center_circle_diameter: 1.54
border_strip_min_width: 0.7
penalty_robot_start: 1.0
