output:
  file:
    enabled: true
    path: DataStream/
  network:
    enabled: true
    pub_port: 12000
    sub_port: 12001
    high_water_mark: 50
    max_image_fps: 10
    max_classified_image_fps: 10

# Select which data to send
reaction_handles:
  # Overview information for the dashboard, designed for minimum bandwidth
  overview: true
  # Statistics about reactions, modules and runtimes
  reaction_statistics: false
  # Data for Chart tool in NUsight
  data_points: false
  # Info from the game controller
  game_controller: false
  # Info about subsumption
  subsumption: true
  # Info about behaviour
  behaviour: true
  # Motor positions, orientation, etc.
  sensors: true
  # Localisation state estimates and uncertainties
  localisation: true
  # Vision data
  image: false # Raw image
  classified_image: false # Colour classified
  goals: false # Detected goals in vision space
  balls: false # Detected balls in vision space
  # Field drawn objects such as an arrow, sphere, etc
  draw_objects: false
  vision_lines: false
